version: '3'

services:
    web:
        build:
            context: ./
            target: runner
        volumes:
            - .:/app
        command: npm start
        ports: 
            - "3000:3000"
        environment:
            NODE_ENV: production